### ISSUE TITLE
remove the 3 decimals of average salary on mouse hover (to be consistent with min and max)

### ISSUE THREAD

**Issue by Guillaume-Cojan** [Guillaume-Cojan/Landing_jobs#74]
![Screenshot from 2021-07-19 18-11-26](https://user-images.githubusercontent.com/78540300/126183502-56381077-7c70-47f6-83df-0088e6985c52.png)

**Comment by anca2196** [comment]
possible solution: in models on backend, "SELECT ROUND(AVG( xxxx ),0) ...."

**Comment by Guillaume-Cojan** [comment]
Proposed solution works but backend deployment to Heroku is blocked for now. We decide to postpone this issue for after the demo day.
